In [1]:
import pandas as pd

In [2]:
adult_train = pd.read_csv("./adult/adult_trainset.csv")
adult_test = pd.read_csv("./adult/adult_testset.csv")

In [13]:
adult_train

,Unnamed: 0,Age,Workclass,Fnlwgt,Education,Education-num,Marital-status,Occupation,Relationship,Race,Sex,Capital-gain,Capital-loss,Hours-per-week,Native-country,Target,Cluster
0,7662,0.118670,0.285829,-0.895058,0.421658,1.128996,0.048399,0.485342,0.106689,0.263855,0.313955,-0.147502,-0.218673,0.756794,0.254411,0,1
1,17310,-0.490566,0.218918,1.970757,0.062950,-2.402221,0.048399,0.007092,0.106689,0.263855,0.113783,-0.147502,-0.218673,-2.165095,0.054455,0,3
2,7445,-0.338257,0.218918,-0.180045,0.164328,-0.440434,0.455011,0.225590,0.455728,0.263855,0.313955,-0.147502,-0.218673,0.756794,0.254411,0,1
3,7152,-1.099801,0.218918,-1.483851,0.200180,-0.048076,0.048399,0.225590,0.014343,0.263855,0.313955,-0.147502,-0.218673,-0.078031,0.254411,0,0
4,6506,-1.023647,0.218918,1.191101,0.164328,-0.440434,0.455011,0.041134,0.455728,0.263855,0.313955,-0.147502,-0.218673,-0.912857,0.254411,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16871,6010,-0.262102,0.218918,0.001145,0.421658,1.128996,0.455011,0.270647,0.493599,0.263855,0.113783,-0.147502,-0.218673,-0.912857,0.254411,1,3
16872,24384,0.956369,0.218918,0.388645,0.200180,-0.048076,0.455011,0.225590,0.455728,0.263855,0.313955,-0.147502,4.669585,1.591619,0.254411,1,0
16873,10776,1.184832,0.558659,-0.409070,0.164328,-0.440434,0.455011,0.225590,0.455728,0.263855,0.313955,-0.147502,-0.218673,-0.078031,0.254411,1,1
16874,3612,1.032523,0.387063,4.043523,0.421658,1.128996,0.455011,0.305159,0.455728,0.129972,0.313955,0.890157,-0.218673,-0.078031,0.254411,1,3
16875,13170,1.184832,0.285829,-1.121092,0.564576,1.521353,0.107312,0.448686,0.106689,0.263855,0.313955,-0.147502,-0.218673,0.756794,0.254411,1,3

In [6]:
import numpy as np
randfordata = np.load("../../pretrained/adult_randfor.data.npz", allow_pickle=True)

In [10]:
for k in randfordata.keys():
    print(k)

x_train
x_test
y_train
y_test

In [11]:
X_train = randfordata['x_train']
y_train = randfordata['y_train']

In [12]:
X_train

array([[ 0.11866996,  0.28582866, -0.89505798, ..., -0.21867335,
         0.75679395,  0.25441118],
       [-0.49056568,  0.21891843,  1.97075657, ..., -0.21867335,
        -2.16509452,  0.05445545],
       [-0.33825677,  0.21891843, -0.18004533, ..., -0.21867335,
         0.75679395,  0.25441118],
       ...,
       [ 1.18483233,  0.55865922, -0.40906971, ..., -0.21867335,
        -0.07803133,  0.25441118],
       [ 1.03252342,  0.38706257,  4.04352285, ..., -0.21867335,
        -0.07803133,  0.25441118],
       [ 1.18483233,  0.28582866, -1.12109155, ..., -0.21867335,
         0.75679395,  0.25441118]])